version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout

       # Download and cache dependencies
       - restore_cache:
           keys:
           - v1-dependencies-{{ checksum "build.gradle" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-

       - run: gradle dependencies

       # Save resolved dependencies on cache
       - save_cache:
           paths:
             - ~/.gradle
           key: v1-dependencies-{{ checksum "build.gradle" }}

       - run: ./gradlew build -x integrationTest