version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      # Save resolved dependencies on cache
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build -x integrationTest

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      - persist_to_workspace:
          root: /tmp/worspace
          paths:
            - build/*
#
#  build-docker:
#    docker:
#      - image: "foo"
#    steps:
#      - checkout
#      - attach_workspace:
#        at: /tmp/workspace
#
#
#
#
#
#       - run:
#           name: Build docker image
#           command: |
#             gradle docker
#
#       - run:
#           name: Output docker images
#           command: |
#             docker images